### ISSUE TITLE
Ruby 2.4 support?

### ISSUE THREAD

**Issue by mike-bourgeous** [deseretbook/classy_hash#11]
Ruby 2.4 merges `Fixnum` and `Bignum` into `Integer`.  This breaks the msgpack gem, and will affect some of the logic of the RSpec tests.
- [x] Update msgpack gem used for benchmarking
- [ ] Fix tests that try to distinguish between `Fixnum` and `Bignum`, or limit them to older Ruby versions.

**Comment by mike-bourgeous** [comment]
MessagePack 1.0 seems to compile fine with Ruby 2.4.0-preview1.  However, there are intermittent errors and even a SIGSEGV when running RSpec on 2.4.0-preview1.

**Comment by Papierkorb** [comment]
Any updates on this?

**Comment by samuel-hcl** [comment]
@mike-bourgeous can you please take a look at my pull request regarding this issue? thanks in advance.

**Comment by mike-bourgeous** [comment]
@samuel-hcl Thanks for the PR!  Sorry for the long wait; I don't work at Deseret Book any more and don't get a lot of time for personal code.
