### ISSUE TITLE
Support for array of schemas

### ISSUE THREAD

**Issue by NathanielWroblewski** [deseretbook/classy_hash#19]
Perhaps this is implementation error, but I have a situation similar to this:

``` rb
> child_schema_one = { type: CH::G.enum('one') }
> child_schema_two = { type: CH::G.enum('two') }
> parent_schema = { children: [[child_schema_one, child_schema_two]] }
> hash = { children: [{ type: 'two'}] }
>
> ClassyHash.validate_strict(hash, parent_schema)
RuntimeError: :children[0][:type] is not an element of ["one"]
```

I had expected each schema to be checked before raising.  Is there a way to achieve this?

**Comment by NathanielWroblewski** [comment]
Is this resolved in 0.2.0?  If so, is there a timeline for release?

**Comment by NathanielWroblewski** [comment]
@mike-bourgeous any thoughts?  I hope the contrived example above isn't too unclear.  I realize the above could be solved with a child schema of `type: CH::G.enum('one', 'two')`, but what about having a parent schema with various irreconcilable children schema.  Here is another contrived exampled, but perhaps better illustrates the issue as the two children schema are irreconcilable:

```
employee = { name: String }
machine = { material: String }
office = { contents: [[employee, machine]] }
hash = { contents: [{ material: 'wood' }] }

ClassyHash.validate_strict(hash, office)
RuntimeError: :contents[0] is not valid: contains members not specified in schema
```

**Comment by mike-bourgeous** [comment]
@NathanielWroblewski I think this should improve after #16 is merged.  Here's some of the changed code: https://github.com/deseretbook/classy_hash/pull/16/files#diff-0dc017d1e42f57c405dab04de9d797faL95

I haven't been able to work on ClassyHash lately, but I should be able to wrap up v0.2.0 soon.

**Comment by NathanielWroblewski** [comment]
No worries, @mike-bourgeous, I know that feel.  I was more curious about this being expected behavior or not.  Thank you for the response! I await the update :)  Let me know if I can help in any way.
