### ISSUE TITLE
Implement some sort of "composite" constraint

### ISSUE THREAD

**Issue by ntl** [deseretbook/classy_hash#2]
Consider:

``` ruby
schema = {
  key1: ClassyHash::G.composite(
    String,
    ClassyHash::G.length(4..20),
  },
}
```

This would allow simple constraints to be combined in powerful ways.

Just a feature suggestion; I'm happy to code it up as a PR, but, like the other one, wanted to see if this is in line with your vision for your gem.

(BTW, this gem seems really cool. I've been looking for lightweight schema validation for a while, in order to efficiently sanitize API inputs)

**Comment by mike-bourgeous** [comment]
@ntl What do you think of #17 for composite constraints?  It will be merged to master when ClassyHash version 0.2.0 is released.

**Comment by ntl** [comment]
Read through it, I like it! I must admit, I've changed jobs more than once in the two years since I originally opened the issue, so I had to get back into context.

I think this is the right direction, ruby still could use a lightweight schema validation tool!

**Comment by mike-bourgeous** [comment]
Cool, thanks for your feedback and for submitting the original issue!

**Comment by ntl** [comment]
No problem, glad I could help.
