### ISSUE TITLE
Custom Error Messages

### ISSUE THREAD

**Issue by marcohelmerich** [deseretbook/classy_hash#21]
Hi, I am trying to validate some Hashes, which are used to initialize objects. I would like to return a useful error message to the User like "each container resource needs a distinct name" or sth. Is there any possibility, to achieve that with classy_hash or do you have a hint where to implement that Feature?
Regards, Marco

**Comment by mike-bourgeous** [comment]
[`Proc` validators](https://github.com/deseretbook/classy_hash#procs) can return custom error messages by returning a `String`.  If that doesn't provide enough detail or if the "is not" prefix is bothersome, you can rescue the error from ClassyHash and re-raise with your preferred error message.  Thanks for using ClassyHash!

Although I wrote ClassyHash, I'll note that I don't work for Deseret Book anymore, so I couldn't say whether or where a new feature should be added to be approved.
