### ISSUE TITLE
Conditional presence checks?

### ISSUE THREAD

**Issue by jits** [deseretbook/classy_hash#22]
Hi – thanks for this succinct, performant and very useful library 😃 

Is it possible to check for the presence of a field conditionally? A concrete example below:

```ruby
schema = {
  name: String,
  field_type: Set.new(['text', 'select']),
  options: <should only be present if field_type == 'select'>,
  multiple: <should only be present if field_type == 'select'>
}
```

I know you can use a `Proc`/`lambda`, but it doesn't look like you can access the hash being validated (or ideally, the current hash the field is in, so you can check siblings)? Not sure yet what an elegant solution might be for this particular problem.

Would appreciate your thoughts on how to solve this.

**Comment by mike-bourgeous** [comment]
I haven't tested this, but maybe you could use try using an AND combination of a Proc and a schema on a Hash element:

```ruby
schema = {
  real_schema = CH::G.all(
    ->(h){ do_stuff_with(h) },
    {
      key1: String,
      key2: Integer,
    }
  )
}
```

Does that work?

**Comment by mike-bourgeous** [comment]
Alternatively a multiple choice for each variation, using a constant value for the field_type key, might work, but your error messages will get pretty heinous.

```ruby
schema = {
  real_schema = [
    { name: Set.new(['text']), blah },
    { name: Set.new(['select']), blah },
  ]
}
```
